# Numpy

In [1]:
import numpy as np

In [3]:
myarray = np.array([1,20,25,98,100])

In [4]:
myarray

array([  1,  20,  25,  98, 100])

In [5]:
print(f"the mean is {myarray.mean()}")

the mean is 48.8


In [10]:
print(f"the mean is {myarray.std()}")

the mean is 41.76793028149707


In [11]:
print(f"multiply the array by 2 : {myarray*2}")

multiply the array by 2 : [  2  40  50 196 200]


In [14]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [18]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
b = a * 4

In [29]:
b

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [30]:
input = b.T

In [31]:
input

array([[ 4, 16, 28, 40],
       [ 8, 20, 32, 44],
       [12, 24, 36, 48]])

In [36]:
random_integers = np.random.randint(100, 200, 20)

In [38]:
r = random_integers

In [39]:
even = r[r%2==0]

In [40]:
even

array([156, 138, 178, 198, 132, 104, 104, 194])

In [41]:
slice = even[2:8]

In [42]:
slice

array([178, 198, 132, 104, 104, 194])